[versions]
agp = "9.0.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.3"
kotlin = "2.3.10"
composeBom = "2026.01.01"
# Toast
sonner = "0.3.9"
#animaciones lotties
lotties = "6.7.1"
# Iconos
icons = "1.7.8"
# Koin
koin = "4.1.1"
#Network
ktor = "3.4.0"
# Google credential
credential = "1.5.0"
googleId = "1.2.0"
# Permission
permission = "0.37.3"
# Data Store
datastorePreferences = "1.2.0"
# Ksp
ksp = "2.3.4"
# Room
room = "2.8.4"
# SqliteCipher
roomCipher = "4.13.0"
# Shimmer
shimer = "1.3.3"
animationCore = "1.9.5"
#ConnectionStatus
konnection = "1.4.5"
# Navigation
nav3Core = "1.0.0"
lifecycleViewmodelNav3 = "2.10.0"
kotlinxSerializationCore = "1.10.0"
material3AdaptiveNav3 = "1.3.0-alpha07"
kotlinSerializationCore = "1.10.0"
# Net Images Coil
coil = "2.7.0"
okhttp = "4.11.0"
okio = "3.3.0"
# Blur effect
haze = "1.7.1"
# Persistence
appwrite = "12.0.0"
# DateTime
kotlinxDatetime = "0.7.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
# Toast
multiplatform-toast = { module = "io.github.dokar3:sonner", version.ref = "sonner" }
# lotties
lotties-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lotties" }
# Iconos
androidx-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "icons" }
# Di
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-androidx-compose-navigation = { module = "io.insert-koin:koin-androidx-compose-navigation", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-test-junit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }
#Ktor Client
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-xml = { module = "io.ktor:ktor-serialization-kotlinx-xml", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-logs = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-websocket = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-client-test = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
# Google credential
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credential" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credential" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleId" }
# Permission
compose-permission = { module = "com.google.accompanist:accompanist-permissions", version.ref = "permission" }
# DataStore
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
# Room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
# Sqlite Cipher
room-cipher = { module = "net.zetetic:sqlcipher-android", version.ref = "roomCipher" }
# Shimmer
shimer-compose = { module = "com.valentinilk.shimmer:compose-shimmer", version.ref = "shimer" }
# Connection Status
konnection-status = { module = "dev.tmapps:konnection", version.ref = "konnection" }
# Core Navigation 3 libraries
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationCore" }
androidx-material3-adaptive-navigation3 = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "material3AdaptiveNav3" }
# Coil
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
# Blur Effect
compose-blurEffect-core = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
compose-blurEffect-materials = { module = "dev.chrisbanes.haze:haze-materials", version.ref = "haze" }
# Persistence
sdk-for1-android = { module = "io.appwrite:sdk-for-android", version.ref = "appwrite" }
# DateTime
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidx-room = { id = "androidx.room", version.ref = "room" }
